### ISSUE TITLE
Cannot read property of null errors when getting disconnected while sending lots of messages

### ISSUE THREAD

**Issue by pscanf** [mondora/ddp.js#22]
### Error

```
TypeError: Cannot read property 'send' of null
    at Socket.send (/Users/pscanf/clients/innowatio/performance-tests/node_modules/ddp.js/lib/socket.js:50:27)
    at Socket.<anonymous> (/Users/pscanf/clients/innowatio/performance-tests/node_modules/ddp.js/lib/ddp.js:81:26)
    at Socket.emitEvent (/Users/pscanf/clients/innowatio/performance-tests/node_modules/wolfy87-eventemitter/EventEmitter.js:382:50)
    at Socket.emit (/Users/pscanf/clients/innowatio/performance-tests/node_modules/wolfy87-eventemitter/EventEmitter.js:409:21)
    at Timer.listOnTimeout (timers.js:92:15)
```

### Likely cause

`Socket.emit` is (for now) asynchronous. The error occurs in the following scenario:
`rawSocket` closes. `rawSocket` is hence set to `null` and a `close` event is emitted on the `Socket` instance. In the time between the "emission" of the `close` event and the handler which sets `DDP.status` to `disconnected`, `DDP.method` || `DDP.sub` || `DDP.unsub` is called. That immediately calls `rawSocket.send`, causing the error.

### Possible solutions

1. Make `Queue.process` async (as it were in `1.0.0`)
2. Make `Socket.emit` sync

**Comment by pscanf** [comment]
Fixed with solution 2.
